version: "3"

services:
  users:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: /bin/sh -c "python3 manage.py makemigrations && python3 manage.py
      migrate && python3 manage.py collectstatic --no-input && python3 manage.py
      runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
